version: '3'

services:
  postgres:
    image: postgres:14.10-alpine
    container_name: pix-database-statistics
    ports:
      - '${PIX_DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_DB: db-stats
